version: "3.9"

services:
  db:
    image: postgres:15
    container_name: orders_postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
