services:
  db:
    image: postgres:15
    container_name: orders_postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: orders_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zk_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: orders_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  app:
    image: golang:1.24-bookworm
    container_name: orders_app
    depends_on:
      - db
      - kafka
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_DATABASE: orders
      DB_SSLMODE: disable
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: orders
    command: ["sh", "-c", "go mod download && go run cmd/app/main.go"]
    ports:
      - "8080:8080"
    restart: on-failure

  producer:
    image: golang:1.24-bookworm
    container_name: orders_producer
    depends_on:
      - kafka
    working_dir: /app
    volumes:
      - .:/app
    environment:
      GOPROXY: direct
      GOSUMDB: off
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_DATABASE: orders
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: orders
      GENERATION_INTERVAL: 5s
    command: ["sh", "-c", "go mod download && go run cmd/producer/main.go"]
    restart: on-failure

volumes:
  pg_data:
  zk_data:
  kafka_data:
