version: "3.9"

services:
  db:
    image: postgres:15
    container_name: orders_postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: orders_zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zk_data:/opt/zookeeper-3.4.6/data

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: orders_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/kafka

  app:
    image: golang:1.22
    container_name: orders_app
    depends_on:
      - db
      - kafka
    working_dir: /Users/veraryabova/Desktop/Go/Order-tracker-service
    volumes:
      - .:/Users/veraryabova/Desktop/Go/Order-tracker-service
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_DATABASE: orders
      DB_SSLMODE: disable
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: orders
    command: ["sh", "-c", "go mod download && go run cmd/app/main.go"]
    ports:
      - "8080:8080"

  producer:
    image: golang:1.22
    container_name: orders_producer
    depends_on:
      - kafka
    working_dir: /Users/veraryabova/Desktop/Go/Order-tracker-service
    volumes:
      - .:/Users/veraryabova/Desktop/Go/Order-tracker-service
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: orders
      GENERATION_INTERVAL: 5s
    command: ["sh", "-c", "go mod download && go run cmd/producer/main.go"]

volumes:
  pg_data:
  zk_data:
  kafka_data:
